// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACiuJ_mP_JFOu8p7r-hyoSGgq0I7sjugU',
    appId: '1:431049589588:web:2152a6535de153c4cdbec1',
    messagingSenderId: '431049589588',
    projectId: 'todofinal-8329e',
    authDomain: 'todofinal-8329e.firebaseapp.com',
    storageBucket: 'todofinal-8329e.appspot.com',
    measurementId: 'G-ZN5WVS3VLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5bJ6M__ivckcRepKPJbEwHUuo3nwW8ao',
    appId: '1:431049589588:android:7ba51b5f93b15770cdbec1',
    messagingSenderId: '431049589588',
    projectId: 'todofinal-8329e',
    storageBucket: 'todofinal-8329e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9rJ_cgN3hl0Atam7n6Of3KlV-_F2zdSA',
    appId: '1:431049589588:ios:4c394235a39f2ab7cdbec1',
    messagingSenderId: '431049589588',
    projectId: 'todofinal-8329e',
    storageBucket: 'todofinal-8329e.appspot.com',
    iosClientId: '431049589588-md85p45u2hofvodlbd21pfl6u46v6i72.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9rJ_cgN3hl0Atam7n6Of3KlV-_F2zdSA',
    appId: '1:431049589588:ios:4c394235a39f2ab7cdbec1',
    messagingSenderId: '431049589588',
    projectId: 'todofinal-8329e',
    storageBucket: 'todofinal-8329e.appspot.com',
    iosClientId: '431049589588-md85p45u2hofvodlbd21pfl6u46v6i72.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled8',
  );
}
